//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18408.
// 
#pragma warning disable 1591

namespace WebApplication1.SGR {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SGRConsultasSOAP", Namespace="http://www.example.org/SGRConsultas/")]
    public partial class SGRConsultas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EmpresaXUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback EquiposXEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BodegasXUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModelosXMarcaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SGRConsultas() {
            this.Url = global::WebApplication1.Properties.Settings.Default.WebApplication1_SGR_SGRConsultas;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EmpresaXUsuarioCompletedEventHandler EmpresaXUsuarioCompleted;
        
        /// <remarks/>
        public event EquiposXEmpresaCompletedEventHandler EquiposXEmpresaCompleted;
        
        /// <remarks/>
        public event BodegasXUsuarioCompletedEventHandler BodegasXUsuarioCompleted;
        
        /// <remarks/>
        public event ModelosXMarcaCompletedEventHandler ModelosXMarcaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/SGRConsultas/EmpresaXUsuario", RequestNamespace="http://www.example.org/SGRConsultas/", ResponseNamespace="http://www.example.org/SGRConsultas/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("respuesta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EmpresaUsuario[] EmpresaXUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string coderror, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string detailerror) {
            object[] results = this.Invoke("EmpresaXUsuario", new object[] {
                        usuario});
            coderror = ((string)(results[1]));
            detailerror = ((string)(results[2]));
            return ((EmpresaUsuario[])(results[0]));
        }
        
        /// <remarks/>
        public void EmpresaXUsuarioAsync(string usuario) {
            this.EmpresaXUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void EmpresaXUsuarioAsync(string usuario, object userState) {
            if ((this.EmpresaXUsuarioOperationCompleted == null)) {
                this.EmpresaXUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmpresaXUsuarioOperationCompleted);
            }
            this.InvokeAsync("EmpresaXUsuario", new object[] {
                        usuario}, this.EmpresaXUsuarioOperationCompleted, userState);
        }
        
        private void OnEmpresaXUsuarioOperationCompleted(object arg) {
            if ((this.EmpresaXUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmpresaXUsuarioCompleted(this, new EmpresaXUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/SGRConsultas/EquiposXEmpresa", RequestNamespace="http://www.example.org/SGRConsultas/", ResponseNamespace="http://www.example.org/SGRConsultas/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("respuesta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EmpresaEquipo[] EquiposXEmpresa([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Empresa, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string codError, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string detailError) {
            object[] results = this.Invoke("EquiposXEmpresa", new object[] {
                        Empresa});
            codError = ((string)(results[1]));
            detailError = ((string)(results[2]));
            return ((EmpresaEquipo[])(results[0]));
        }
        
        /// <remarks/>
        public void EquiposXEmpresaAsync(string Empresa) {
            this.EquiposXEmpresaAsync(Empresa, null);
        }
        
        /// <remarks/>
        public void EquiposXEmpresaAsync(string Empresa, object userState) {
            if ((this.EquiposXEmpresaOperationCompleted == null)) {
                this.EquiposXEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEquiposXEmpresaOperationCompleted);
            }
            this.InvokeAsync("EquiposXEmpresa", new object[] {
                        Empresa}, this.EquiposXEmpresaOperationCompleted, userState);
        }
        
        private void OnEquiposXEmpresaOperationCompleted(object arg) {
            if ((this.EquiposXEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EquiposXEmpresaCompleted(this, new EquiposXEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/SGRConsultas/BodegasXUsuario", RequestNamespace="http://www.example.org/SGRConsultas/", ResponseNamespace="http://www.example.org/SGRConsultas/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("respuesta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EmpresaBodegas[] BodegasXUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string empresa, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string codError, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string detailError) {
            object[] results = this.Invoke("BodegasXUsuario", new object[] {
                        usuario,
                        empresa});
            codError = ((string)(results[1]));
            detailError = ((string)(results[2]));
            return ((EmpresaBodegas[])(results[0]));
        }
        
        /// <remarks/>
        public void BodegasXUsuarioAsync(string usuario, string empresa) {
            this.BodegasXUsuarioAsync(usuario, empresa, null);
        }
        
        /// <remarks/>
        public void BodegasXUsuarioAsync(string usuario, string empresa, object userState) {
            if ((this.BodegasXUsuarioOperationCompleted == null)) {
                this.BodegasXUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBodegasXUsuarioOperationCompleted);
            }
            this.InvokeAsync("BodegasXUsuario", new object[] {
                        usuario,
                        empresa}, this.BodegasXUsuarioOperationCompleted, userState);
        }
        
        private void OnBodegasXUsuarioOperationCompleted(object arg) {
            if ((this.BodegasXUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BodegasXUsuarioCompleted(this, new BodegasXUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/SGRConsultas/ModelosXMarca", RequestNamespace="http://www.example.org/SGRConsultas/", ResponseNamespace="http://www.example.org/SGRConsultas/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("respuesta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EmpresaMarcaTipoModelo ModelosXMarca([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string idempresa, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string idtipo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string coderror, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string detailerror) {
            object[] results = this.Invoke("ModelosXMarca", new object[] {
                        idempresa,
                        idtipo});
            coderror = ((string)(results[1]));
            detailerror = ((string)(results[2]));
            return ((EmpresaMarcaTipoModelo)(results[0]));
        }
        
        /// <remarks/>
        public void ModelosXMarcaAsync(string idempresa, string idtipo) {
            this.ModelosXMarcaAsync(idempresa, idtipo, null);
        }
        
        /// <remarks/>
        public void ModelosXMarcaAsync(string idempresa, string idtipo, object userState) {
            if ((this.ModelosXMarcaOperationCompleted == null)) {
                this.ModelosXMarcaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModelosXMarcaOperationCompleted);
            }
            this.InvokeAsync("ModelosXMarca", new object[] {
                        idempresa,
                        idtipo}, this.ModelosXMarcaOperationCompleted, userState);
        }
        
        private void OnModelosXMarcaOperationCompleted(object arg) {
            if ((this.ModelosXMarcaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModelosXMarcaCompleted(this, new ModelosXMarcaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SGRConsultas/")]
    public partial class EmpresaUsuario {
        
        private string codEmpresaField;
        
        private string nomEmpresaField;
        
        private string nomUsuarioField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodEmpresa {
            get {
                return this.codEmpresaField;
            }
            set {
                this.codEmpresaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NomEmpresa {
            get {
                return this.nomEmpresaField;
            }
            set {
                this.nomEmpresaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NomUsuario {
            get {
                return this.nomUsuarioField;
            }
            set {
                this.nomUsuarioField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SGRConsultas/")]
    public partial class ModeloEquipos {
        
        private string idmodeloField;
        
        private string nommodeloField;
        
        private string codarticuloField;
        
        private string nomarticuloField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idmodelo {
            get {
                return this.idmodeloField;
            }
            set {
                this.idmodeloField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nommodelo {
            get {
                return this.nommodeloField;
            }
            set {
                this.nommodeloField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codarticulo {
            get {
                return this.codarticuloField;
            }
            set {
                this.codarticuloField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomarticulo {
            get {
                return this.nomarticuloField;
            }
            set {
                this.nomarticuloField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SGRConsultas/")]
    public partial class Marcas {
        
        private string idmarcaField;
        
        private string nommarcaField;
        
        private ModeloEquipos[] modelosField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idmarca {
            get {
                return this.idmarcaField;
            }
            set {
                this.idmarcaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nommarca {
            get {
                return this.nommarcaField;
            }
            set {
                this.nommarcaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("modelos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ModeloEquipos[] modelos {
            get {
                return this.modelosField;
            }
            set {
                this.modelosField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SGRConsultas/")]
    public partial class TipoEquipo {
        
        private string idtipoequipoField;
        
        private Marcas[] marcasField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idtipoequipo {
            get {
                return this.idtipoequipoField;
            }
            set {
                this.idtipoequipoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("marcas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Marcas[] marcas {
            get {
                return this.marcasField;
            }
            set {
                this.marcasField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SGRConsultas/")]
    public partial class EmpresaMarcaTipoModelo {
        
        private string idempresaField;
        
        private TipoEquipo[] tiposequiposField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idempresa {
            get {
                return this.idempresaField;
            }
            set {
                this.idempresaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("tiposequipos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TipoEquipo[] tiposequipos {
            get {
                return this.tiposequiposField;
            }
            set {
                this.tiposequiposField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SGRConsultas/")]
    public partial class Bodegas {
        
        private string codAlmacenField;
        
        private string nomAlmacenField;
        
        private string ciudadField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codAlmacen {
            get {
                return this.codAlmacenField;
            }
            set {
                this.codAlmacenField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomAlmacen {
            get {
                return this.nomAlmacenField;
            }
            set {
                this.nomAlmacenField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SGRConsultas/")]
    public partial class EmpresaBodegas {
        
        private string codEmpresaField;
        
        private Bodegas[] almacenesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codEmpresa {
            get {
                return this.codEmpresaField;
            }
            set {
                this.codEmpresaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("almacenes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Bodegas[] almacenes {
            get {
                return this.almacenesField;
            }
            set {
                this.almacenesField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SGRConsultas/")]
    public partial class Equipos {
        
        private string codequipoField;
        
        private string nomequipoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codequipo {
            get {
                return this.codequipoField;
            }
            set {
                this.codequipoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomequipo {
            get {
                return this.nomequipoField;
            }
            set {
                this.nomequipoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SGRConsultas/")]
    public partial class EmpresaEquipo {
        
        private string codempresaField;
        
        private string nomempresaField;
        
        private Equipos[] equiposField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codempresa {
            get {
                return this.codempresaField;
            }
            set {
                this.codempresaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomempresa {
            get {
                return this.nomempresaField;
            }
            set {
                this.nomempresaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("equipos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Equipos[] equipos {
            get {
                return this.equiposField;
            }
            set {
                this.equiposField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void EmpresaXUsuarioCompletedEventHandler(object sender, EmpresaXUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmpresaXUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmpresaXUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmpresaUsuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmpresaUsuario[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string coderror {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string detailerror {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void EquiposXEmpresaCompletedEventHandler(object sender, EquiposXEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EquiposXEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EquiposXEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmpresaEquipo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmpresaEquipo[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string codError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string detailError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void BodegasXUsuarioCompletedEventHandler(object sender, BodegasXUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BodegasXUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BodegasXUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmpresaBodegas[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmpresaBodegas[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string codError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string detailError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ModelosXMarcaCompletedEventHandler(object sender, ModelosXMarcaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModelosXMarcaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModelosXMarcaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmpresaMarcaTipoModelo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmpresaMarcaTipoModelo)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string coderror {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string detailerror {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591